config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "clients#index"
  resources :clients do
    resources :logs
  end
  resources :records
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user
  has_many :logs, dependent: :destroy
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :client
  has_one :record, dependent: :destroy
  accepts_nested_attributes_for :record
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :log
end

app/models/user.rb
class User < ApplicationRecord
  has_many :clients, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_post, only: %i[edit update destroy]

  def index
    @clients = current_user.clients.order(:id)
  end

  def new
    @client = Client.new
  end

  def create
    client = current_user.clients.create!(client_params)
  end

  def show
    @client = Client.find(params[:id])
    @logs = Log.all
  end

  def edit
  end

  def update
    @client.update!(client_params)
  end

  def destroy
    @client.destroy!
  end

  private

  def client_params
    params.require(:client).permit(:name, :gender, :age, :address)
  end

  def set_post
    @client = current_user.clients.find(params[:id])
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_post, only: %i[index new edit update destroy]

  def index
    @logs = @client.logs.order(:id)
  end

  def show
    @log = @client.logs.find(params[:id])
  end

  def new
    @log = Log.new
    @log.build_record
  end

  def create
    client = current_user.clients.find(params[:client_id])
    @log = client.logs.create!(log_params)
  end

  def edit
    @log = @client.logs.find(params[:id])
  end

  def update
    log = @client.logs.find(params[:id])
    log.update!(log_params)
    redirect_to client_logs_path
  end

  def destroy
    log = @client.logs.find(params[:id])
    log.destroy!
    redirect_to client_logs_path
  end

  private

  def log_params
    params.require(:log).permit(:date, :fee, record_attributes: [:id, :subjective, :objective, :assessment, :plan, :memo, :record_id]).merge(client_id: params[:client_id])
  end

  def set_post
    @client = current_user.clients.find(params[:client_id])
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def index
    @records = Record.all
  end

  def new
    @record = Record.new
  end

  def create
    @log = @client.logs.find(params[:log_id])
    @record = @log.records.create!(record_params)
  end

  def show
    @record = Record.find(params[:id])
  end

  def edit
    @record = Record.find(params[:id])
  end

  def update
    record = Record.find(params[:id])
    record.update!
  end

  def destroy
    record = Record.find(params[:id])
    record.destroy!
  end

  private

  def record_params
    params.require(:record).permit(:subjective, :objective, :assessment, :plan, :memo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clients/_form.html.erb
<%= form_with model: @client, local: true do |f| %>
  <p>
    <%= f.label :name, "名前" %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :gender, "性別" %>
    <%= f.text_field :gender %>
  </p>
  <p>
    <%= f.label :age, "年齢" %>
    <%= f.number_field :age %>
  </p>
  <p>
    <%= f.label :address, "住所" %>
    <%= f.text_area :address %>
  </p>
  <%= f.submit "登録" %>
<% end %>

app/views/clients/create.html.erb
<h1>登録完了</h1>
<%= link_to "一覧画面へ", clients_path %>

app/views/clients/destroy.html.erb
<h1>削除完了</h1>
<%= link_to "一覧画面へ", clients_path %>

app/views/clients/edit.html.erb
<h2>顧客情報修正</h2>
<%= render "form" %>
<%= link_to "戻る", clients_path%>

app/views/clients/index.html.erb
<%= link_to "新規顧客登録", new_client_path %>
<h1>顧客一覧</h1>
<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>性別</th>
      <th>年齢</th>
      <th>住所</th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <p>
          <td><%= client.name %></td>
          <td><%= client.gender %></td>
          <td><%= client.age %></td>
          <td><%=client.address %></td>
        </p>
        <p>
          <td><%= link_to "削除", client_path(client), method: :delete, data: {confirm: "削除しますか?"} %>
            <%= link_to "編集", edit_client_path(client) %>
            <%= link_to "詳細", client %></td>
        </p>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/clients/new.html.erb
<h2>新規顧客登録</h2>
<%= render "form" %>
<%= link_to "戻る", clients_path %>

app/views/clients/show.html.erb
<h1>顧客詳細</h1>
<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>性別</th>
      <th>年齢</th>
      <th>住所</th>
    </tr>
  </thead>
  <tbody>
    <p>
      <td><%= @client.name %></td>
      <td><%= @client.gender %></td>
      <td><%= @client.age %></td>
      <td><%= @client.address %></td>
    </p>
  </tbody>
</table>
<%= link_to "通院履歴登録", new_client_log_path(@client) %>
<%= link_to "通院履歴一覧", client_logs_path(@client) %>

app/views/clients/update.html.erb
<h1>更新完了</h1>
<%= link_to "一覧画面へ", clients_path %>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <%= link_to "顧客一覧", root_path %>
  <%= link_to "新規投稿ページ", new_client_path %>
  <%= "【ログイン中のアドレス】#{current_user.email}" %>
  <%= link_to "アカウント編集", edit_user_registration_path %>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" } %>
<% else %>
  <%= link_to "ログイン", new_user_session_path %>
  <%= link_to "新規登録", new_user_registration_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yokunaru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/logs/_form.html.erb
<%= form_with model: [@client, @log], local:true do |f| %>
  <div>
    <%= f.label :date, "日付" %>
    <%= f.date_field :date %>
  </div>
  <div>
    <%= f.label :fee, "料金" %>
    <%= f.text_field :fee %>
  </div>
  <%= f.fields_for :record do |r_f| %>
    <div>
      <p><%= r_f.label :subjective, "S（subjective）：主観的情報" %></p>
      <p><%= r_f.text_area :subjective %></p>
    </div>
    <div>
      <p><%= r_f.label :objective, "O（objective）： 客観的情報" %></p>
      <p><%= r_f.text_area :objective %></p>
    </div>
    <div>
      <p><%= r_f.label :assessment, "A（assessment）： 評価" %></p>
      <p><%= r_f.text_area :assessment %></p>
    </div>
    <div>
      <p><%= r_f.label :plan, "P（plan）： 計画（治療）" %></p>
      <p><%= r_f.text_area :plan %></p>
    </div>
    <div>
      <p><%= r_f.label :memo, "その他メモ" %></p>
      <p><%= r_f.text_area :memo %></p>
    </div>
  <% end %>
  <%= f.submit "登録" %>
<% end %>

app/views/logs/create.html.erb
<h1>登録完了</h1>
<%= link_to "一覧画面へ", client_logs_path %>

app/views/logs/edit.html.erb
<h1>通院履歴編集</h1>
<%= render "form" %>

app/views/logs/index.html.erb
<%= link_to "施術履歴一覧", records_path %>
<table>
  <thead>
    <tr>
      <th>日付</th>
      <th>金額</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @logs.each do |log| %>
        <p>
          <td><%= log.date %></td>
          <td><%= log.fee %></td>
        </p>
        <p>
          <td><%= link_to "削除", client_log_path(@client, log), method: :delete, data: {confirm: "削除しますか?"} %>
            <%= link_to "編集", edit_client_log_path(@client, log) %>
            <%= link_to "詳細", record_path %>
          </td>
        </p>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/logs/new.html.erb
<h1>新規入力</h1>
<%= render "form" %>

app/views/logs/show.html.erb
<h3>詳細</h3>
<%= @log.date %>
<%= @log.fee%>

app/views/records/create.html.erb
<h1>登録完了</h1>
<%= link_to "一覧画面へ", records_path %>

app/views/records/index.html.erb
<%= link_to "投稿画面へ", new_record_path %>
<% @records.each do |record| %>
  <p>
    <%= record.subjective %>
    <%= record.objective %>
    <%= record.assessment %>
    <%= record.plan %>
    <%= record.memo %>
  </p>
<% end %>

app/views/records/new.html.erb
<h1>新規登録</h1>
<%= form_with model: @record, local: true do |f| %>
  <div>
    <p><%= f.label :subjective, "S（subjective）：主観的情報" %></p>
    <p><%= f.text_area :subjective %></p>
  </div>
  <div>
    <p><%= f.label :objective, "O（objective）： 客観的情報" %></p>
    <p><%= f.text_area :objective %></p>
  </div>
  <div>
    <p><%= f.label :assessment, "A（assessment）：評価" %></p>
    <p><%= f.text_area :assessment %></p>
  </div>
  <div>
    <p><%= f.label :plan, "P（plan）：計画（治療）" %></p>
    <p><%= f.text_area :plan %></p>
  </div>
  <div>
    <p><%= f.label :memo, "その他メモ" %></p>
    <p><%= f.text_area :memo %></p>
  </div>
  <%= f.submit "登録" %>
<% end %>

app/views/records/show.html.erb
<% @records.each do |record| %>
  <p><%= "S（subjective）：主観的情報" %></p>
  <p><%= record.subjective %></p>
  <p><%= "O（objective）：客観的情報" %></p>
  <p><%= record.objective %></p>
  <p><%= "A（assessment）：評価" %></p>
  <p><%= record.assessment %></p>
  <p><%= "P（plan）：計画（治療）" %></p>
  <p><%= record.plan %></p>
  <p><%= "その他メモ" %></p>
  <p><%= record.memo %></p>
<% end %>